---
- name: Copy the ipmi_exporter systemd service file
  template:
    src: ipmi_exporter.service.j2
    dest: /etc/systemd/system/ipmi_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart ipmi_exporter
