---
- name: restart ipmi_exporter
  become: true
  systemd:
    daemon_reload: true
    name: ipmi_exporter
    state: restarted

- name: reload ipmi_exporter
  become: true
  systemd:
    name: ipmi_exporter
    state: reloaded
